name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Lint & format checks
      - name: ESLint
        run: pnpm run lint # ESLint is the standard JS/TS linter [[3]]

      - name: Prettier
        run: pnpm run format:check

      - name: dprint
        run: pnpm run dprint:check

      - name: Biome
        run: pnpm run biome:check

      - name: TypeScript typecheck
        run: pnpm run typecheck

      # Build only after checks pass
      - name: Build
        run: pnpm run build
